#!/usr/bin/env bash

#________________________________________________________________________
#                _             
#    _ __  _ __ | | ____ _ ____
#   | '_ \| '_ \| |/ / _` |_  /
#   | | | | |_) |   < (_| |/ / 
#   |_| |_| .__/|_|\_\__, /___|
#         |_|        |___/     
#   
# npkgz » simply pack nodejs applications into tgz archive
#________________________________________________________________________
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
# --
# Copyright 2020-2024 Andi Dittrich <https://andidittrich.com>
#________________________________________________________________________

_VERSION="1.0.0"
_LICENSE="MPL-2.0"
_REPOSITORY="https://github.com/npkgz/npkgz-build"

show_usage(){
    cat << EOF
Usage: npkgz <command> [args...]

Options:
    -h,--help               Displays this help
    -v,--version            Displays version

Commands:  
    build <dir>             Pack application
    update <dir>            Build and trigger deploy hook

EOF
    exit 0
}

show_version(){
    cat << EOF
npkgz » simply pack nodejs applications into tgz archive » v${_VERSION}
License: Mozilla Public License, v. 2.0 (MPL-2.0) https://opensource.org/licenses/MPL-2.0
Repository: ${_REPOSITORY}
EOF
    exit 0
}

# simple processing for help+versioning commands
[ "$1" = "--help" ] || [ "$1" = "-h" ] || [ -z "$1" ] && show_usage
[ "$1" = "--version" ] || [ "$1" = "-v" ] && show_version

# Exit on Error
set -e

# basedir
BASEDIR="$( cd "$( dirname "$(realpath ${BASH_SOURCE[0]})" )" && pwd )"
WORKINGDIR="$(pwd)"

# extract target name; remove trailing slash
TARGET_NAME="${2%/}"

# load functions
source $BASEDIR/lib/bash-functions

# intro
# ---------------------------------------
function npkgz_intro(){
    print_heading " >> npkgz"
    _print_colorized '\x1B[1m' "npkgz » simply pack nodejs applications into tgz archive\n"
}

# validate paths
npkgz_prepare(){
    
    # image name provided ?
    if [ -z "$1" ]; then
        panic "image path not provided"
    fi

    # extract path
    PKG_PATH="$(realpath $1)"

    # path exists ?
    if [ ! -d "$PKG_PATH" ]; then
        panic "image path not provided"
    fi

    # extract image name (strip trailing slash)
    PKG_NAME="$(basename $PKG_PATH)"

    # options file exists ?
    if [ ! -f "$PKG_PATH/.npkgz" ]; then
        panic "options file doesn't exist"
    fi

    # entrypoint exists ?
    if [ ! -f "$PKG_PATH/main.js" ]; then
        panic "entrypoint doesn't exist"
    fi

    # dist dir exists ?
    if [ ! -d "$PKG_PATH/.dist" ]; then
        panic "dist dir doesn't exist"
    fi

    # show info
    log_info "package-name: ${PKG_NAME}"
    log_info "package-path: ${PKG_PATH}"
}

# trigger cached build
npkgz_build(){
    log_info "bulding package"

    # load config
    source $PKG_PATH/.npkgz

    # create tmp build dir
    BUILD_DIR=$(mktemp -d)

    # source dirs to array
    IFS=' ' read -ra sourceDirs <<<"$NPKGZ_INCLUDE"

    # copy files
    for dir in "${sourceDirs[@]}"; do
        log_info "copying [$dir].."
        cp -R ${PKG_PATH}/$dir ${BUILD_DIR}
    done

    # copy package files
    cp ${PKG_PATH}/package.json ${BUILD_DIR}
    cp ${PKG_PATH}/yarn.lock ${BUILD_DIR}
    cp ${PKG_PATH}/main.js ${BUILD_DIR}

    # install dependencies
    cd ${BUILD_DIR}
    yarn install --production

    # create package
    tar cfz ${PKG_PATH}/.dist/${PKG_NAME}.tgz -C ${BUILD_DIR} .

    # cleanup
    rm -rf ${BUILD_DIR}
}

# run hook
# ---------------------------------------
function npkgz_hook_exec(){
    log_info "hook [$1] triggered"

    # hook set ?
    if [ -z "$1" ]; then
        log_error "invalid hook call"
        return
    fi

    # hook file exists ?
    if [ ! -f $WORKINGDIR/.hooks/$1 ]; then
        return
    fi

    # executable ?
    if [ ! -x $WORKINGDIR/.hooks/$1 ]; then
        panic "hook [$WORKINGDIR/.hooks/$1] is not executable"
    fi

    # run hook
    log_info "running hook [$1].."
    HOOK_FN="hook_$1"
    source $WORKINGDIR/.hooks/$1
    $HOOK_FN
}


# Command Dispatching
# ---------------------------------------
case "$1" in
    check)
        npkgz_intro
        npkgz_prepare $2
        exit 0
    ;;

    build)
        npkgz_intro
        npkgz_prepare $2
        npkgz_build
        exit 0
    ;;

    update)
        npkgz_intro
        npkgz_prepare $2
        npkgz_build
        npkgz_hook_exec "deploy"
        exit 0
    ;;

    *)
        show_usage
        exit 1
    ;;
esac